//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMBC.EasyFactor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMBC.EasyFactor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap army_officer_icon_48 {
            get {
                object obj = ResourceManager.GetObject("army_officer_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap banknote_icon_48 {
            get {
                object obj = ResourceManager.GetObject("banknote_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bar_chart_icon_48 {
            get {
                object obj = ResourceManager.GetObject("bar_chart_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap boss_icon_48 {
            get {
                object obj = ResourceManager.GetObject("boss_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Briefcase_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Briefcase_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_icon_48 {
            get {
                object obj = ResourceManager.GetObject("calculator_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cash_register_icon_48 {
            get {
                object obj = ResourceManager.GetObject("cash_register_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check_user_icon_48 {
            get {
                object obj = ResourceManager.GetObject("check_user_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coins_icon_48 {
            get {
                object obj = ResourceManager.GetObject("coins_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Column_Chart_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Column_Chart_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap credit_card_icon_48 {
            get {
                object obj = ResourceManager.GetObject("credit_card_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Disk_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Disk_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap engineer_icon_48 {
            get {
                object obj = ResourceManager.GetObject("engineer_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FOMSLOGO {
            get {
                object obj = ResourceManager.GetObject("FOMSLOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap footballer_icon_48 {
            get {
                object obj = ResourceManager.GetObject("footballer_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gold_bullion_icon_48 {
            get {
                object obj = ResourceManager.GetObject("gold_bullion_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap green_dollar_icon_48 {
            get {
                object obj = ResourceManager.GetObject("green_dollar_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoice_icon_48 {
            get {
                object obj = ResourceManager.GetObject("invoice_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_chart_icon_48 {
            get {
                object obj = ResourceManager.GetObject("line_chart_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Man_Black_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Man_Black_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Man_Brown_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Man_Brown_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Man_DBrown_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Man_DBrown_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Man_Grey_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Man_Grey_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Man_Red_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Man_Red_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Menu_Down_icon_32x32 {
            get {
                object obj = ResourceManager.GetObject("Menu_Down_icon_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Menu_Title {
            get {
                object obj = ResourceManager.GetObject("Menu_Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Menu_Up_icon_32x32 {
            get {
                object obj = ResourceManager.GetObject("Menu_Up_icon_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_icon_48 {
            get {
                object obj = ResourceManager.GetObject("payment_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap people_icon_48 {
            get {
                object obj = ResourceManager.GetObject("people_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pie_chart_icon_48 {
            get {
                object obj = ResourceManager.GetObject("pie_chart_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Printer_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Printer_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap safe_icon_48 {
            get {
                object obj = ResourceManager.GetObject("safe_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopping_cart_icon_48 {
            get {
                object obj = ResourceManager.GetObject("shopping_cart_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbox_icon_48 {
            get {
                object obj = ResourceManager.GetObject("Toolbox_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User_Add_32x32 {
            get {
                object obj = ResourceManager.GetObject("User_Add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User_Edit_32x32 {
            get {
                object obj = ResourceManager.GetObject("User_Edit_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_group_icon_48 {
            get {
                object obj = ResourceManager.GetObject("user_group_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User_icon_48 {
            get {
                object obj = ResourceManager.GetObject("User_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_info_icon_48 {
            get {
                object obj = ResourceManager.GetObject("user_info_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User_Remove_32x32 {
            get {
                object obj = ResourceManager.GetObject("User_Remove_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserMgr_icon_32x32 {
            get {
                object obj = ResourceManager.GetObject("UserMgr_icon_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users_icon_48 {
            get {
                object obj = ResourceManager.GetObject("users_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yen_coin_icon_48 {
            get {
                object obj = ResourceManager.GetObject("yen_coin_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yen_coins_icon_48 {
            get {
                object obj = ResourceManager.GetObject("yen_coins_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yen_icon_48 {
            get {
                object obj = ResourceManager.GetObject("yen_icon_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
